language: ruby
cache: bundler
sudo: false
rvm: 2.2.0
before_script: rake db:test:prepare
script: rake test
env:
  global:
  - HEADLESS=true
  - CI=true
  - secure: KC6iFFO1StiwBR6qZOzjTIgzV1Wm3q3rRsmt67+eO+9v0KhJ630ke0s40L23573OieqaedaMKPU2Q2xfhs3h+3l9Xko2CkdNm/1AWujofxSBd31rnFshQ+M0anqiz4iD4ZARtTv2zpPfjMO94asXgrc7FvJ7WYp3laVhnd3+b3Y=
  - secure: es2VvXh4m1jk8dWfTQflFHObPkuCz6ZwUdcgXQICEmws9jHiq88ulWuxv3HG8+nUMochqHyNtAJvfsVBh84xM/v5KZqrurmvPPqooGokri2vLaDeIL0syV86Yzk1gm0fzIsWrRR7xFQRrDCuVDXpDmiGff9iiUkYUfa+1cGh/CY=
  - secure: fxJ5u8QWS4VQIQ5iE7mrKwxnSrG4pWIh/IHREDxabH1EgXfCMhEP4AbCiaasrc6kYPEXvJNgHKXeZSqk5j41SIO5SCJr+x+8ov9byZcU0kzc4oA5mhBnAfwwX4SsGVKJOF5nyfBBwwR3vk/9zwT+jZW0TRUIjZD9DfZidGIktW4=
  - secure: NlXBrFXXcLvxYY1g5aRTOvzlz04PNoWtkP71iLaTSqqC/C4rKKagDWtQbWXAtJucNYY5FBzSkozsRiOw5mNl1zd44UlLLqMaZ9pnE12W3Ifxd8aLlAMFdYQzebSn5vJeC70ewvZZwLoo6ErxaeV0zxT09q+xU8DjVqxIwCwKadc=
  - secure: A2LLg1TKoL3ARtRwqA9C7UVL9EXEhTI9zZO8IK1LGgtOHdcrhr8GiEg9HgwZatItISdG1eZ2fBDk0Ze6q4CXPJFQNt4xJgCJjmezlcWKHH3G4wVCe6WJkUeqvEXtNnXkNbK86VaGTaHoOR21I4lLYnB1giqWN6ZT0zddKFUx3ks=
  - secure: EvvSQIZj3eXbF+lU2d24hd6ap39tTTvZekgRGTX9UG7909WI/fPkyMv4UCYYIDeFVz8rd8FD+COsiloMezq6i/TQpD6Sy/s/51DYL4CWbtS3m4DrAe3b5fCVS1El8TSrWCUDgoZYF3tr25Kvnh3l8XpuuhjNEDcytTZWQlUwZ+U=
  - secure: XufEJfkpwP3gfo/nz3CWrJalPATvs0PdTz3GwGWsg0RQ7ypO+oT7r0QTeeJCueUysaK96Xw/hIzfBhiAXw2vh4+mdgOxmQabmW9j7gjn7TIrAGoPBSDkBFO2UYmDLfMM/YfqObVgQzWYZY+6/EFj0UT8PiEQ22gU5W/Z3R5Q2Dc=
  - secure: G+B66Xy7JRChf7g0rrgSTX3CM6m2SPbVhy/oBpOhySsAKdmkAnP/A84glGd5gttWx+oEKFJ9GQCdlxnJwuKu/yBZO2zfTLoOGLyzoaCEGzkFOh4qBdqUZfe85EPKrgr3VmSzavyW+KQwk7kdSk5kcQCvQIQ50YVJgVb/ajonP9U=
  - secure: TYhVpqfwykr3kIxTR0H3o87FH3xluAdO6aQCCQpvAv8mn63iCd9/fHXz07dKP7cqCtku/Glt8PufXFmoqiIKB2vpZSH3yH/wIiwuYgwlOJ9WulM3nUSW/bzdW3itzr7pXeb08WFnNC0Cf7LE2pWzbJ4kDHODXkXlg3E91LLobcg=
  - secure: JK8Y9Vm0bRi0ketkYeeU9FomrFPHpWqEejofX72BcTKcrnUe53QZ1NmZgJjk1+nzSZSw+CGFN/jJeEMwcBwobT4w2+cw7PVZI8znUpTOh7pBBs7H2F3Z9YB4cWkPRkH0nqZjCUIRkF/e9tC9f/D0mvTBsa0Hrb/NfExjq6+Tt18=
  - secure: KRzGAdEV4uEE3RA4j2cWGL1CF6co2Am12nrNuWFJnoRjpkeWrIOLHPwrJ/KE7+mAFpDfe+YcsAwKDUHMF4x1lzrwBgoNZSLRn0ImaT+AZWy+IMUZsxbhznC27hvm1La+As/h/3JIbyaKUxhCDjx+9LWzbYUUgUEciQvsOLajtDk=
  - secure: M0LXmqXMxgY8/s5SjgvB8mbcMv5uM5Qv8Ca26uBNvWhQSQzBM24ElSbsUEgr2Y2M61Vw5C+gwq3neTUQYzGikNgeG0mXWgBzRY69nqmCS2xSRGR1uvHlibibu5Ql/IayvEZ7e21+U2cg18eia7QvrZFOd1nbCkRnUuPtFEzpwLY=
  - secure: f7cFtYYgoBgaAfOCQe6LV29WfQ7pvS0UP/Bg0hNKEFvHe+bVHNw77ILUaR/F6LLze5LFn92lPJtBfVy6NvY2pXsOoWD04EeQDnXI4xyMWj9yd8qSu8IwULmSj+0GzC0RkirgFpOEaPPkQoM8ScqX98qC/Vuh3wPsj1Ygb80UEt4=
  - secure: UV+5JJnSFwmyRfLowhPwoZITZLEqjEVGmDR+kEpfbGIWeAQhdnxpBY5rms6mZAVb9MSH7jbQgiyMOq0jM8rcR7XpUGTG17NUxsEO7GmdJiDcuPp629miUduy0eigmPxSVujhpyG/PQyGsfIHL0i3jTufk7HYhhuGAh9LMYIViak=
